%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\msb3\Downloads\projetoAM-master\Bases_de_Dados\yeast.data.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/06/10 10:45:23

%% Initialize variables.
filename = strcat(pwd, '\Bases_de_Dados\yeast.data.txt');
%% Format string for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
%   column10: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*10s%6f%6f%6f%6f%6f%6f%6f%6f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray([1, 2, 3, 4, 5, 6, 7, 8]) = cellfun(@(x) num2cell(x), dataArray([1, 2, 3, 4, 5, 6, 7, 8]), 'UniformOutput', false);
data = [dataArray{1:end-1}];

[~, ~, map] = unique(data(:,end));
data = [cell2mat(data(:,1:end-1)), map];
%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;