%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Program Files\MATLAB\MATLAB Production Server\R2015a\bin\iris.data.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/04/09 09:57:06

%% Initialize variables.
filename = strcat(pwd, '\Bases_de_Dados\iris.data.txt');
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray([1, 2, 3, 4]) = cellfun(@(x) num2cell(x), dataArray([1, 2, 3, 4]), 'UniformOutput', false);
data = [dataArray{1:end-1}];

[~, ~, map] = unique(data(:,end));
data = [cell2mat(data(:,1:end-1)), map];

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
